# Generated by Django 4.1.7 on 2023-03-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customer_id_customuser_is_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='customer status'),
        ),
    ]
