# Generated by Django 4.1.4 on 2022-12-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contactdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
        ),
    ]
