# Generated by Django 4.1.7 on 2023-03-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='customers',
            field=models.ManyToManyField(through='accounts.CustomerAddress', to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='addresses',
            field=models.ManyToManyField(through='accounts.CustomerAddress', to='accounts.address'),
        ),
    ]
