# Generated by Django 4.1.4 on 2022-12-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('books', 'Books'), ('home', 'Home'), ('clothes', 'Clothes'), ('health', 'Health'), ('electronic', 'Electronic'), ('misc', 'Misc')], default='misc', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover', models.ImageField(upload_to='covers/')),
                ('category', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
